CREATE SCHEMA IF NOT EXISTS shoppingbuddy;

CREATE TABLE shoppingbuddy.users
(
    id                       int8 GENERATED BY DEFAULT AS IDENTITY,
    first_name               varchar(255),
    last_name                varchar(255),
    email                    varchar(255),
    created_on               timestamp,
    image_url                varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE shoppingbuddy.group
(
    id                        int8 GENERATED BY DEFAULT AS IDENTITY,
    name                      varchar(255),
    description               TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE shoppingbuddy.group_member
(
    id                       int8 GENERATED BY DEFAULT AS IDENTITY,
    name                     varchar(255),
    description              varchar(255),
    PRIMARY KEY (id)
);
